---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  # Label for your resources, default-flavor is fine
  name: "default-flavor"
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "benchmark-cluster-queue"
spec:
  # Define the total resources this queue can manage
  namespaceSelector: {}
  resourceGroups:
  - coveredResources: ["cpu", "memory"]
    flavors:
    - name: "default-flavor"
      resources:
      - name: "cpu"
        nominalQuota: 50
      - name: "memory"
        nominalQuota: 100Gi
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  name: "guidellm-jobs"
  namespace: llm-d-inference-scheduling
spec:
  clusterQueue: "benchmark-cluster-queue" 
